routes/web.php
<?php

use App\Http\Controllers\KeahlianController;
use App\Http\Controllers\PegawaiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/keahlian', KeahlianController::class)
    ->middleware('auth');

Route::resource('/pegawai', PegawaiController::class)
    ->middleware('auth');

app/Models/Keahlian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Keahlian extends Model
{
    use HasFactory;

    protected $table = 'keahlian';

    protected $primaryKey = 'keahlian_id';

    // Kalau PK bukan angka dan autoincrement
    // public $incrementing = false;
    // protected $keyType = 'string';

    // protected $fillable = ['nama'];

    // protected $hidden = ['password'];

    protected $guarded = [];

    public function pegawai()
    {
        return $this->hasMany(Pegawai::class, 'keahlian_id', 'keahlian_id');
    }
}

app/Http/Controllers/KeahlianController.php
<?php

namespace App\Http\Controllers;

use App\Models\Keahlian;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class KeahlianController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_keahlian = Keahlian::all();
        // $query = Keahlian::select(['keahlian.nama as nama_keahlian', 'pegawai.nama as nama_pegawai'])
        //     ->join('pegawai', 'keahlian.keahlian_id', '=', 'pegawai.keahlian_id')
        //     ->limit(5)
        //     ->get();

        // return response()->json($query);

        return view('keahlian.index', compact('list_keahlian'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('keahlian.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string'
        ]);

        // dd($request->all());
        // $k = new Keahlian();
        // $k->nama = $request->nama;
        // $k->save();

        Keahlian::create($request->all());

        return redirect()->route('keahlian.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Keahlian  $keahlian
     * @return \Illuminate\Http\Response
     */
    public function show(Keahlian $keahlian)
    {
        dd($keahlian);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Keahlian  $keahlian
     * @return \Illuminate\Http\Response
     */
    public function edit(Keahlian $keahlian)
    {
        return view('keahlian.edit', compact('keahlian'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Keahlian  $keahlian
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Keahlian $keahlian)
    {
        $request->validate([
            'nama' => 'required|string'
        ]);

        $keahlian->nama = $request->nama;
        $keahlian->save();

        return redirect()->route('keahlian.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Keahlian  $keahlian
     * @return \Illuminate\Http\Response
     */
    public function destroy(Keahlian $keahlian)
    {
        $keahlian->delete();

        $response['error'] = false;
        $response['message'] = 'Data berhasil dihapus.';
        
        return response()->json($response, 200);
    }
}

resources/views/keahlian/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Tambah Keahlian') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('keahlian.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label for="nama" class="col-sm-2 col-form-label">Keahlian</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="nama" id="nama"
                                      value="{{ old('nama') }}"  placeholder="Nama keahlian">

                                    @error('nama')
                                        {{-- <span class="invalid-feedback" role="alert"> --}}
                                            <strong>{{ $message }}</strong>
                                        {{-- </span> --}}
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary mt-3">Simpan</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <!-- halo adlin -- !>
@endpush

resources/views/keahlian/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Ubah Keahlian') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('keahlian.update', $keahlian->keahlian_id) }}">
                            @csrf
                            @method('PATCH')

                            <div class="form-group row">
                                <label for="nama" class="col-sm-2 col-form-label">Keahlian</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="nama" id="nama"
                                      value="{{ old('nama') ?? $keahlian->nama }}"  placeholder="Nama keahlian">

                                    @error('nama')
                                        {{-- <span class="invalid-feedback" role="alert"> --}}
                                            <strong>{{ $message }}</strong>
                                        {{-- </span> --}}
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary mt-3">Perbaharui</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <!-- halo adlin -- !>
@endpush

resources/views/keahlian/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Daftar Keahlian') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <a class="btn btn-primary btn-sm mb-3" href="{{ route('keahlian.create') }}">Tambah</a>

                        <table class="table table-striped table-bordered table-hover" id="tbl-form">
                            <thead>
                                <tr>
                                    <th width="10%" class="text-center">ID</th>
                                    <th>Nama Keahlian</th>
                                    <th width="25%" class="text-center">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($list_keahlian as $row)
                                    <tr>
                                        <td>{{ $row->keahlian_id }}</td>
                                        <td>{{ $row->nama }}</td>
                                        <td>
                                            <a href="{{ route('keahlian.edit', $row->keahlian_id) }}"
                                                class="btn btn-sm btn-warning">Ubah</a> &nbsp;&nbsp;&nbsp;
                                            <a href="javascript:void(0);" data-id="{{ $row->keahlian_id }}"
                                                class="btn btn-sm btn-danger hapus">Hapus</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Nama Keahlian</th>
                                    <th>Aksi</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        'use strict'

        $(function() {
            $('#tbl-form').delegate('a.hapus', 'click', function(e) {
                let that = $(this),
                    id = that.data('id');

                Swal.fire({
                    title: 'Konfirmasi Hapus?',
                    text: "Ente yaqueen mau hapus data",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Iya dong'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: '{{ url('keahlian') }}/' + id,
                            method: 'POST',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            },
                            data: {
                                _method: 'DELETE'
                            },
                            success: function(result) {
                                if (result.error == false) {
                                    Swal.fire(
                                        'Notifikasi',
                                        result.message,
                                        'success'
                                    );

                                    window.location.reload();
                                }
                            }
                        });
                    }
                });
            });
        });
    </script>
@endpush

resources/views/keahlian/show.blade.php
{{-- {{ $keahlian->keahlian_id }}<br>
{{ $keahlian->nama }}<br> --}}

@foreach ($keahlian as $item)
    {{ $item->nama }}<br>
    {{ $item->nip }}<br>
    {{ $item->alamat }}<br>
    
    @foreach ($item->pegawai as $item2)
        {{ $item2->nama }}<br>
    @endforeach
    <br><br>
@endforeach