routes/web.php
<?php

use App\Http\Controllers\KeahlianController;
use App\Http\Controllers\PegawaiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/keahlian', KeahlianController::class)
    ->middleware('auth');

Route::resource('/pegawai', PegawaiController::class)
    ->middleware('auth');

app/Models/Pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    use HasFactory;

    protected $table = 'pegawai';

    protected $primaryKey = 'pegawai_id';

    // Kalau PK bukan angka dan autoincrement
    // public $incrementing = false;
    // protected $keyType = 'string';

    // Di set jika ingin menggunakan mass asignment
    // protected $fillable = ['nama', 'nip', 'alamat', 'tanggal_lahir', 'keahlian_id', 'status'];

    // Di set jika ada kolom / field yg ingin dihide
    // protected $hidden = ['password'];

    // Di set jika ada kolom yg ingin di proteksi dari mass asignment, jika isi blank maka semua field dapat diassign melalui form submit
    protected $guarded = [];

    public function keahlian()
    {
        return $this->belongsTo(Keahlian::class, 'keahlian_id', 'keahlian_id');
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Keahlian;
use App\Models\Pegawai;
use Illuminate\Http\Request;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keahlians = Keahlian::all();
        $pegawais = Pegawai::select(['pegawai_id', 'pegawai.nama as nm_pegawai', 'nip', 'tanggal_lahir', 'alamat', 'keahlian.nama as nm_keahlian'])
            ->join('keahlian', 'pegawai.keahlian_id', '=', 'keahlian.keahlian_id');

        if ($request->has('nama')) {
            $pegawais->where('pegawai.nama', 'like', '%' . $request->nama . '%');
        }

        if ($request->has('keahlian')) {
            $pegawais->where('pegawai.keahlian_id', $request->keahlian);
        }

        $pegawais->get();

        // $pegawais
        // dd($pegawais);

        return view('pegawai.index', compact('pegawais', 'keahlians'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function show(Pegawai $pegawai)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function edit(Pegawai $pegawai)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pegawai $pegawai)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pegawai $pegawai)
    {
        //
    }
}

resources/views/pegawai/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mb-3">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Advanced Search') }}</div>
                    <div class="card-body">
                        <div class="row">
                            <form method="GET" action="{{ route('pegawai.index') }}">
                                <div class="form-group row mb-3">
                                    <label for="keahlian" class="col-sm-2 col-form-label">Keahlian</label>
                                    <div class="col-sm-10">
                                        <select name="keahlian" id="keahlian" class="form-control">
                                            <option value="">-- Filter Keahlian</option>
                                            @foreach ($keahlians as $r)
                                                <option value="{{ $r->keahlian_id }}">{{ $r->nama }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row mb-3">
                                    <label for="nama" class="col-sm-2 col-form-label">Nama Pegawai</label>
                                    <div class="col-sm-10">
                                        <input type="text" name="nama" id="nama" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="" class="col-sm-2 col-form-label"></label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-success" id="btn-filter">Cari</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Daftar Keahlian') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <a class="btn btn-primary btn-sm mb-3" href="{{ route('pegawai.create') }}">Tambah</a>

                        <table class="table table-striped table-bordered table-hover" id="tbl-form">
                            <thead>
                                <tr>
                                    <th width="10%" class="text-center">ID</th>
                                    <th>Nama</th>
                                    <th>NIP</th>
                                    <th>Tgl. Lahir</th>
                                    <th>Alamat</th>
                                    <th>Keahlian</th>
                                    <th width="25%" class="text-center">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($pegawais as $row)
                                    <tr>
                                        <td>{{ $row->pegawai_id }}</td>
                                        <td>{{ $row->nm_pegawai }}</td>
                                        <td>{{ $row->nip }}</td>
                                        <td>{{ $row->tanggal_lahir }}</td>
                                        <td>{{ $row->alamat }}</td>
                                        <td>{{ $row->nm_keahlian }}</td>
                                        <td>
                                            <a href="{{ route('pegawai.edit', $row->pegawai_id) }}"
                                                class="btn btn-sm btn-warning">Ubah</a> &nbsp;&nbsp;&nbsp;
                                            <a href="javascript:void(0);" data-id="{{ $row->pegawai_id }}"
                                                class="btn btn-sm btn-danger hapus">Hapus</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Nama</th>
                                    <th>NIP</th>
                                    <th>Tgl. Lahir</th>
                                    <th>Alamat</th>
                                    <th>Keahlian</th>
                                    <th>Aksi</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        'use strict'

        $(function() {
            $('#tbl-form').delegate('a.hapus', 'click', function(e) {
                let that = $(this),
                    id = that.data('id');

                Swal.fire({
                    title: 'Konfirmasi Hapus?',
                    text: "Ente yaqueen mau hapus data",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Iya dong'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: '{{ url('pegawai') }}/' + id,
                            method: 'POST',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            },
                            data: {
                                _method: 'DELETE'
                            },
                            success: function(result) {
                                if (result.error == false) {
                                    Swal.fire(
                                        'Notifikasi',
                                        result.message,
                                        'success'
                                    );

                                    window.location.reload();
                                }
                            }
                        });
                    }
                });
            });
        });
    </script>
@endpush